//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransaction
    {
        public int BankTranID { get; set; }
        public System.DateTime TranDate { get; set; }
        public string TransactionNo { get; set; }
        public int TransactionType { get; set; }
        public decimal Amount { get; set; }
        public int BankID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> AnotherBankID { get; set; }
        public string ChecqueNo { get; set; }
        public string Remarks { get; set; }
        public int CusDealerID { get; set; }
    
        public virtual Bank Bank { get; set; }
    }
}
