//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int BranchID { get; set; }
        public string Code { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string AccountNo { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal TotalAmount { get; set; }
        public int BankID { get; set; }
    
        public virtual Branch Branches1 { get; set; }
        public virtual Branch Branch1 { get; set; }
    }
}
