//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardTypeSetup
    {
        public int CardTypeSetupID { get; set; }
        public string Code { get; set; }
        public int BankID { get; set; }
        public int CardTypeID { get; set; }
        public decimal Percentage { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual CardType CardType { get; set; }
    }
}
