//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashCollection
    {
        public int CashCollectionID { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public System.DateTime EntryDate { get; set; }
        public decimal Amount { get; set; }
        public string AccountNo { get; set; }
        public string MBAccountNo { get; set; }
        public string BKashNo { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CheckNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public decimal AdjustAmt { get; set; }
        public string ReceiptNo { get; set; }
        public decimal BalanceDue { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> RemindDate { get; set; }
        public int RemindPeriod { get; set; }
        public int RemindStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
