//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditSalesDetail
    {
        public int CSDetailsID { get; set; }
        public Nullable<System.DateTime> MonthDate { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> InstallmentAmt { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public int CreditSalesID { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<int> ScheduleNo { get; set; }
        public string Remarks { get; set; }
        public int IsUnExpected { get; set; }
        public decimal HireValue { get; set; }
        public decimal NetValue { get; set; }
        public decimal LastPayAdjustment { get; set; }
        public decimal CardPaidAmount { get; set; }
        public decimal CardTypeSetupID { get; set; }
        public decimal DepositChargePercent { get; set; }
        public int BankTranID { get; set; }
        public Nullable<System.DateTime> RemindDateForInstallment { get; set; }
    
        public virtual CreditSale CreditSale { get; set; }
    }
}
