//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmpSalaries = new HashSet<EmpSalary>();
        }
    
        public int EmployeeID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string ContactNo { get; set; }
        public string EmailID { get; set; }
        public string NID { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string PresentAdd { get; set; }
        public string PermanentAdd { get; set; }
        public int DesignationID { get; set; }
        public decimal GrossSalary { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Designation Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpSalary> EmpSalaries { get; set; }
    }
}
