//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure
    {
        public int ExpenditureID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Purpose { get; set; }
        public decimal Amount { get; set; }
        public int ExpenseItemID { get; set; }
        public string VoucherName { get; set; }
        public int Status { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual ExpenseItem ExpenseItem { get; set; }
    }
}
