//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyStock
    {
        public int MonthlyStockID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime Month { get; set; }
        public decimal Opening { get; set; }
        public decimal Closing { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
