//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class POrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POrder()
        {
            this.POrderDetails = new HashSet<POrderDetail>();
        }
    
        public int POrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string ChallanNo { get; set; }
        public int SupplierID { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal TDiscount { get; set; }
        public decimal TotalAmt { get; set; }
        public decimal RecAmt { get; set; }
        public decimal PaymentDue { get; set; }
        public decimal TotalDue { get; set; }
        public int Status { get; set; }
        public decimal PPDisAmt { get; set; }
        public decimal NetDiscount { get; set; }
        public decimal TDPer { get; set; }
        public decimal LaborCost { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal Adjustment { get; set; }
        public decimal TransportCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POrderDetail> POrderDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual User User { get; set; }
    }
}
