//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CreditSaleProducts = new HashSet<CreditSaleProduct>();
            this.DamageProducts = new HashSet<DamageProduct>();
            this.MonthlyStocks = new HashSet<MonthlyStock>();
            this.POProductDetails = new HashSet<POProductDetail>();
            this.POrderDetails = new HashSet<POrderDetail>();
            this.ReturnDetails = new HashSet<ReturnDetail>();
            this.SOrderDetails = new HashSet<SOrderDetail>();
            this.StockDetails = new HashSet<StockDetail>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int ProductID { get; set; }
        public string Code { get; set; }
        public string ProductName { get; set; }
        public string PicturePath { get; set; }
        public int CategoryID { get; set; }
        public decimal SalesRate { get; set; }
        public decimal PurchaseRate { get; set; }
        public int CompanyID { get; set; }
        public decimal PackSize { get; set; }
        public decimal WarningQty { get; set; }
        public int ModelID { get; set; }
        public int UnitType { get; set; }
        public decimal ShortQty { get; set; }
        public string PhotoPath { get; set; }
        public decimal BoxQty { get; set; }
        public int ProductType { get; set; }
        public string CompressorWarrenty { get; set; }
        public string PanelWarrenty { get; set; }
        public string MotorWarrenty { get; set; }
        public string SparePartsWarrenty { get; set; }
        public string ServiceWarrenty { get; set; }
        public decimal GSTPerc { get; set; }
        public decimal CGSTPerc { get; set; }
        public decimal SGSTPerc { get; set; }
        public decimal IGSTPerc { get; set; }
        public decimal Tax { get; set; }
        public decimal MaxQty { get; set; }
        public string BarCode { get; set; }
        public decimal CostPrice { get; set; }
        public decimal RetailPrice { get; set; }
        public Nullable<bool> quickmanu { get; set; }
        public Nullable<bool> labelprint { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditSaleProduct> CreditSaleProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DamageProduct> DamageProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlyStock> MonthlyStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POProductDetail> POProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POrderDetail> POrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnDetail> ReturnDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOrderDetail> SOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockDetail> StockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
