//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSStatus
    {
        public int SMSStatusID { get; set; }
        public string Code { get; set; }
        public int SMSFormateID { get; set; }
        public int SendingStatus { get; set; }
        public int NoOfSMS { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ContactNo { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string SMS { get; set; }
        public string ResponseMsg { get; set; }
    
        public virtual SMSFormate SMSFormate { get; set; }
        public virtual User User { get; set; }
    }
}
