//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOrder()
        {
            this.SOrderDetails = new HashSet<SOrderDetail>();
        }
    
        public int SOrderID { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public decimal SubTotal { get; set; }
        public decimal VATPercentage { get; set; }
        public decimal VATAmount { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal PPDiscountAmt { get; set; }
        public decimal TDPercentage { get; set; }
        public decimal TDAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal PaymentDue { get; set; }
        public decimal RecAmount { get; set; }
        public Nullable<decimal> BackAmount { get; set; }
        public string Remarks { get; set; }
        public int CustomerID { get; set; }
        public decimal TotalDue { get; set; }
        public int Status { get; set; }
        public string SerialNo { get; set; }
        public decimal Adjustment { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal NetDiscount { get; set; }
        public Nullable<System.DateTime> RemindDate { get; set; }
        public int RemindPeriod { get; set; }
        public int RemindStatus { get; set; }
        public int BankTranID { get; set; }
        public decimal CardPaidAmount { get; set; }
        public int CardTypeSetupID { get; set; }
        public decimal DepositChargePercent { get; set; }
        public decimal CashPaidAmount { get; set; }
        public Nullable<int> CardTypeID { get; set; }
        public Nullable<int> branchid { get; set; }
        public bool ShiftEndStatus { get; set; }
        public Nullable<int> shiftid { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOrderDetail> SOrderDetails { get; set; }
        public virtual User User { get; set; }
    }
}
