//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockDetail()
        {
            this.CreditSaleProducts = new HashSet<CreditSaleProduct>();
            this.SOrderDetails = new HashSet<SOrderDetail>();
        }
    
        public int SDetailID { get; set; }
        public string StockCode { get; set; }
        public int ProductID { get; set; }
        public string IMENO { get; set; }
        public Nullable<int> StockID { get; set; }
        public int Status { get; set; }
        public int ColorID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public decimal SalesRate { get; set; }
        public Nullable<decimal> PRate { get; set; }
        public Nullable<int> POrderDetailID { get; set; }
        public decimal Quantity { get; set; }
        public int GodownID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditSaleProduct> CreditSaleProducts { get; set; }
        public virtual DamageProduct DamageProduct { get; set; }
        public virtual POrderDetail POrderDetail { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOrderDetail> SOrderDetails { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
