//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.StockDetails = new HashSet<StockDetail>();
        }
    
        public int StockID { get; set; }
        public string StockCode { get; set; }
        public System.DateTime EntryDate { get; set; }
        public decimal Quantity { get; set; }
        public int ProductID { get; set; }
        public decimal PMPrice { get; set; }
        public decimal LPPrice { get; set; }
        public int ColorID { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> GodownID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockDetail> StockDetails { get; set; }
        public virtual Godown Godown { get; set; }
    }
}
