//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CustomerLedger
    {
        public int CustomerID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal OpeningDue { get; set; }
        public decimal SalesGrandTotal { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal RecAmount { get; set; }
        public decimal AdjustInSales { get; set; }
        public decimal BackAmount { get; set; }
        public decimal CreditSalesDue { get; set; }
        public decimal CashRecAmt { get; set; }
        public decimal AdjustInCashRec { get; set; }
        public Nullable<decimal> ActualDue { get; set; }
        public decimal SystemDue { get; set; }
        public Nullable<decimal> Diff { get; set; }
        public string Remarks { get; set; }
    }
}
