//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INVENTORY.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SupplierLedger
    {
        public int SupplierID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal GrandTotal { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal PaidAmt { get; set; }
        public decimal AdjustInCashDelivery { get; set; }
        public decimal CashDelivery { get; set; }
        public Nullable<decimal> ActualDue { get; set; }
        public decimal SystemDue { get; set; }
        public Nullable<decimal> Diff { get; set; }
        public string Remarks { get; set; }
    }
}
